// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/TourFlowPro.tsx": () => import("../components/mockups/TourFlowPro.tsx"),
  "./components/mockups/tourflow/Cockpit.tsx": () => import("../components/mockups/tourflow/Cockpit.tsx"),
  "./components/mockups/tourflow/Expenses.tsx": () => import("../components/mockups/tourflow/Expenses.tsx"),
  "./components/mockups/tourflow/GuestLiveView.tsx": () => import("../components/mockups/tourflow/GuestLiveView.tsx"),
  "./components/mockups/tourflow/PinLock.tsx": () => import("../components/mockups/tourflow/PinLock.tsx"),
  "./components/mockups/tourflow/Scanner.tsx": () => import("../components/mockups/tourflow/Scanner.tsx"),
  "./components/mockups/tourflow/TourContext.tsx": () => import("../components/mockups/tourflow/TourContext.tsx"),
  "./components/mockups/tourflow/ui.tsx": () => import("../components/mockups/tourflow/ui.tsx")
};
